import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Privacy Policy | HeicToPng',
    description: 'Comprehensive Privacy Policy for HeicToPng.org. Learn about our zero-upload architecture, data handling, and your rights.',
};

export default function PrivacyPage() {
    return (
        <article className="max-w-4xl mx-auto py-16 px-6 text-gray-700">
            <h1 className="text-4xl font-extrabold text-gray-900 mb-6">Privacy Policy</h1>
            <p className="mb-10 text-gray-500"><strong>Effective Date:</strong> December 17, 2025</p>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">1. Introduction and Scope</h2>
                <p className="mb-4 leading-relaxed">
                    Welcome to <strong>HeicToPng.org</strong> (the "Service," "we," "us," or "our"). We recognize that your privacy is a serious matter, and we are committed to protecting the personal information you share with us. This Privacy Policy outlines our practices regarding the collection, use, and disclosure of your information when you access our website and use our HEIC to PNG conversion tools.
                </p>
                <p className="mb-4 leading-relaxed">
                    By accessing or using the Service, you agree to the collection and use of information in accordance with this policy. If you do not agree with any part of this Privacy Policy, please discontinue use of our Service immediately.
                </p>
                <p className="mb-4 leading-relaxed">
                    Unlike many other file conversion services, <strong>HeicToPng.org operates primarily as a client-side tool</strong>. This means that for the majority of our operations, your files are processed directly within your web browser and are not uploaded to our servers. This unique architecture provides you with an enhanced level of privacy and security compared to traditional server-side converters.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">2. Definitions and Interpretation</h2>
                <p className="mb-4 leading-relaxed">To ensure clarity, the following terms are defined as follows:</p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li><strong>"Service"</strong> refers to the HeicToPng.org website and its associated conversion tools.</li>
                    <li><strong>"Personal Data"</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
                    <li><strong>"Usage Data"</strong> is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>"Cookies"</strong> are small pieces of data stored on a User’s device.</li>
                    <li><strong>"Data Controller"</strong> means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.</li>
                    <li><strong>"User"</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
                </ul>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">3. The "Zero-Upload" Architecture</h2>
                <p className="mb-6 leading-relaxed">Our commitment to your privacy is built into the code of our Service.</p>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">3.1. Local File Processing</h3>
                <p className="mb-4 leading-relaxed">
                    When you use our tool to convert HEIC files to PNG, the process occurs locally on your device using WebAssembly and modern browser technologies. <strong>We do not upload your image files to our servers.</strong> Because your files never leave your computer or mobile device:
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li>We do not have access to your photos.</li>
                    <li>We cannot view, store, copy, or share your content.</li>
                    <li>There is no risk of your files being intercepted during transit to our servers, as no such transit occurs for the conversion process.</li>
                </ul>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">3.2. No Data Retention Policy</h3>
                <p className="mb-4 leading-relaxed">
                    Since we do not receive your files, we do not need a data retention policy for user content. There are no files for us to delete because we never stored them in the first place. Once you close your browser tab or refresh the page, any data processed in your browser's temporary memory is instantly cleared by your operating system.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">4. Information We Collect and Use</h2>
                <p className="mb-6 leading-relaxed">
                    While we do not collect your files, we collect certain non-personal information to maintain and improve the Service.
                </p>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">4.1. Usage Data</h3>
                <p className="mb-4 leading-relaxed">
                    We may collect information that your browser sends whenever you visit our Service ("Usage Data"). This Usage Data may include information such as:
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li>Your computer's Internet Protocol address (e.g., IP address).</li>
                    <li>Browser type and browser version.</li>
                    <li>The pages of our Service that you visit.</li>
                    <li>The time and date of your visit.</li>
                    <li>The time spent on those pages.</li>
                    <li>Unique device identifiers and other diagnostic data.</li>
                </ul>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">4.2. Cookies and Tracking Technologies</h3>
                <p className="mb-4 leading-relaxed">
                    We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier.
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                    <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings (e.g., dark mode or language).</li>
                    <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                    <li><strong>Advertising Cookies:</strong> Cookies used to serve you with advertisements that may be relevant to you and your interests.</li>
                </ul>
                <p className="mb-4 leading-relaxed">
                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">5. Third-Party Service Providers</h2>
                <p className="mb-6 leading-relaxed">
                    We may employ third-party companies and individuals ("Service Providers") to facilitate our Service, to provide the Service on our behalf, to perform Service-related services, or to assist us in analyzing how our Service is used.
                </p>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">5.1. Analytics</h3>
                <p className="mb-4 leading-relaxed">
                    We may use third-party Service Providers to monitor and analyze the use of our Service.
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li><strong>Google Analytics:</strong> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on.</li>
                </ul>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">5.2. Advertising</h3>
                <p className="mb-4 leading-relaxed">
                    We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li><strong>Google AdSense:</strong> We may use Google AdSense to display ads. Google uses cookies to serve ads based on your prior visits to our website or other websites. Google's use of advertising cookies enables it and its partners to serve ads to users based on their visit to your sites and/or other sites on the Internet.</li>
                </ul>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">6. General Data Protection Regulation (GDPR)</h2>
                <p className="mb-6 leading-relaxed">
                    If you are from the European Economic Area (EEA), HeicToPng.org's legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
                </p>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">6.1. Your Data Protection Rights</h3>
                <p className="mb-4 leading-relaxed">
                    HeicToPng.org aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. Because we do not store user files, the "Right to Erasure" regarding file content is automatically satisfied by our client-side architecture. Regarding Usage Data (like IP addresses), you have the right:
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li><strong>To access and receive a copy</strong> of the Personal Data we hold about you.</li>
                    <li><strong>To rectify</strong> any Personal Data held about you that is inaccurate.</li>
                    <li><strong>To request deletion</strong> of Personal Data held about you.</li>
                    <li><strong>To data portability</strong> for the information you provide to HeicToPng.org.</li>
                </ul>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">7. California Consumer Privacy Act (CCPA)</h2>
                <p className="mb-6 leading-relaxed">This section provides additional details for California residents.</p>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">7.1. Categories of Personal Information Collected</h3>
                <p className="mb-4 leading-relaxed">
                    In the preceding 12 months, we may have collected the following categories of personal information: identifiers (such as IP address), internet or other electronic network activity information (such as browsing history).
                </p>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">7.2. Your Rights Under CCPA</h3>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li><strong>Right to Know:</strong> You have the right to request that we disclose certain information to you about our collection and use of your personal information over the past 12 months.</li>
                    <li><strong>Right to Delete:</strong> You have the right to request that we delete any of your personal information that we collected from you and retained, subject to certain exceptions.</li>
                    <li><strong>Right to Non-Discrimination:</strong> We will not discriminate against you for exercising any of your CCPA rights.</li>
                </ul>

                <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">7.3. "Do Not Sell My Personal Information"</h3>
                <p className="mb-4 leading-relaxed">
                    We do not sell your personal files or data. We may work with advertising partners who collect data via cookies. You can opt-out of these by adjusting your browser settings.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">8. Security of Data</h2>
                <p className="mb-4 leading-relaxed">
                    The security of your data is important to us. Remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>
                <p className="mb-4 leading-relaxed">
                    However, our <strong>Client-Side Processing</strong> model significantly reduces security risks compared to server-side competitors, as your sensitive files are never exposed to our internal networks or potential database breaches. All traffic to our website is encrypted via <strong>SSL/TLS (HTTPS)</strong> to protect against eavesdropping.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">9. Links to Other Sites</h2>
                <p className="mb-4 leading-relaxed">
                    Our Service may contain links to other sites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">10. Children's Privacy</h2>
                <p className="mb-4 leading-relaxed">
                    Our Service does not address anyone under the age of 13 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Children have provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">11. Changes to This Privacy Policy</h2>
                <p className="mb-4 leading-relaxed">
                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
            </section>

            <section className="mb-12">
                <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-5 pb-2 border-b">12. Contact Us</h2>
                <p className="mb-4 leading-relaxed">
                    If you have any questions about this Privacy Policy, please contact us:
                </p>
                <ul className="list-disc pl-6 space-y-2 mb-4 leading-relaxed">
                    <li>By email: <a href="mailto:privacy@heictopng.org" className="text-blue-600 hover:underline">privacy@heictopng.org</a></li>
                </ul>
            </section>
        </article>
    );
}
